apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: education-skills-work-employment-dev
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1024Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
