apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: workload-measurement-preprod.hmpps.service.justice.gov.uk
  namespace: hmpps-workload-preprod
spec:
  secretName: hmpps-workload-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - workload-measurement-preprod.hmpps.service.justice.gov.uk
