kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-workload-prod-admin
  namespace: hmpps-workload-prod
subjects:
  - kind: Group
    name: "github:manage-a-sentence"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
