---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: hmpps-workload-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: hmpps-workload-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: hmpps-workload-prod
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: hmpps-workload-prod
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "jobs"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
      - "apps"
      - "networking.k8s.io"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-monitoring
  namespace: hmpps-workload-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: hmpps-workload-prod
roleRef:
  kind: Role
  name: monitoring
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-deployment
  namespace: hmpps-workload-prod
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: hmpps-workload-prod
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: monitoring
  namespace: hmpps-workload-prod
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - '*'
---
