# description: |
#               This GitHub Action will check every namespace amended in a PR, take the RBAC team name and confirm 
#               the user is in that team.
name: Check if user can amend namespace

on:
  pull_request

env:
  PR_OWNER: ${{ github.event.pull_request.user.login }}
  BRANCH: ${{ github.head_ref }}
  GITHUB_OAUTH_TOKEN: ${{ secrets.CHECK_GITHUB_TEAM }}

jobs:
  rbac-permissions-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@master

      - name: owner of PR
        run: |
          echo "$PR_OWNER" && echo "$BRANCH"

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.all }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            if [[ "${added_modified_file}" == *"live"* ]]; then
              echo "${added_modified_file}" | awk -F/ '{print $3}' >> files
            fi
          done
          cat files

      - name: Check the PR owner is in the correct rbac group
        id: review_pr
        uses: ministryofjustice/github-actions/env-permissions-check@add-rbac-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
