# description: |
#               This GitHub Action will check every namespace amended in a PR, take the RBAC team name and confirm 
#               the user is in that team.
name: Check if user can amend namespace

on:
  pull_request

env:
  PR_OWNER: ${{ github.event.pull_request.user.login }}
  # GITHUB_OAUTH_TOKEN: ${{ secrets.CHECK_GITHUB_TEAM }}

jobs:
  checksum-compare:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@master

      - name: owner of PR
        run: |
          echo "$PR_OWNER"

      - name: Run git diff against repository
        run: |
          git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master) > changes

