name: Ingress checker
on:
  pull_request

jobs:
  ingress-checker:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout PR code
        uses: actions/checkout@master

      - name: Get all files changed in PR
        id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.live.cloud*'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.all }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            namespace=$(echo added_modified_file | awk -F/ '{print $3}')
            [[ ${#namespace} -eq 0 ]] && echo "This PR doesn't contain changes in the live cluster." && exit 0

            cmd=$(curl -s i -H "Accept: application/json" https://reports.cloud-platform.service.justice.gov.uk/ingress_weighting  | jq -r '.weighting_ingress[] | select(.namespace=="${cmd}")')
            [[ ${#cmd} -eq 0 ]] || echo "The following ingress resources need changing:" ${cmd} && echo "action_state=${namespace}" >> $GITHUB_ENV && exit 1
          done

          echo "The namespace doesn't have any ingress annotation conflicts." && exit 0

      - name: Create comment in the PR
        uses: peter-evans/create-or-update-comment@v1

        if: failure()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Live-1 namespace "${{ env.action_state }}" contains an ingress resource that doesn't have the correct annotations. Please check: https://reports.cloud-platform.service.justice.gov.uk/ingress_weighting
